apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: produce-service
  name: produce-service
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      run: produce-service
  template:
    metadata:
      labels:
        run: produce-service
    spec:
      containers:
      - image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
        name: produce-service
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 5"]
---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: produce-service
  name: produce-service-port
  namespace: default
spec:
  selector:
    run: produce-service
  ports:
    - port: 8080
      name: http
